### ISSUE TITLE
Where could I edit to change the personal information?

### ISSUE THREAD

**Issue by garywzh** [nauzethc/ghost-material#7]
Like the URLs linked to these buttons(twitter, github, google plus).

**Comment by nauzethc** [comment]
Personal information is harcoded on theme beause Ghost platform doesn't store any social link for invidual accounts, so if your blog has many authors you'll have to change social links on client side.

Otherwise, social media links are harcoded on `partials/author.hbs` (post page), `default.hbs`(footer section) and `index.hbs` (navbar). Replace `href` attributes with your personal links or add new links for other social networks.

**Comment by garywzh** [comment]
I tried that(change href links and restart ghost), but it seems not working.

**Comment by nauzethc** [comment]
Could you paste your edited template?

**Comment by garywzh** [comment]
```
<div class="author">
  <div class="author--media">
    <nav class="fabs">
      <a class="fab large ripple twitter" href="https://twitter.com/garywzh">
        <i class="mdi mdi-twitter"></i>
      </a>
      <a class="fab large ripple github" href="https://github.com/garywzh">
        <i class="mdi mdi-github-circle"></i>
      </a>
      <a class="fab large ripple google-plus" href="https://plus.google.com/117864139814756022466">
        <i class="mdi mdi-google-plus"></i>
      </a>
    </nav>
    <img class="image" src="{{image}}" />
  </div>
  <div class="author--info">
    <h5 class="name">{{name}}</h5>
    <p class="bio">{{bio}}</p>
  </div>
</div>

```

This is the author.hbs file.

**Comment by nauzethc** [comment]
It's ok. I've checked my personal blog and they are exactly the same. Those are for the floating buttons that appears when you hover/touch author's picture at the end of the post.

**Comment by garywzh** [comment]
Well, I got it. I thought they are top bar button links.

Thanks you for making this great theme.

Stay awesome
